#include<iostream.h>
#include<conio.h>
void hello();	//prototype declaration or Function declaration
void main()	//System Defined Function
{
hello();	//User Defined Function
hello();       //calling Function
hello();
hello();
getch();
}
void hello()	//called Function
{
cout<<"Welcome to C++ Programming"<<endl;
cout<<"Introduced By Bjarne StrousStroup"<<endl;
cout<<"Its Object Oriented Programming Language"<<endl;
cout<<"Its Partially Supports OOPs Concepts"<<endl;
}
